name: Bug report
description: Reportar um bug
title: "[bug] "
labels: ["type:bug"]
body:
  - type: textarea
    id: summary
    attributes:
      label: Resumo
      description: O que está quebrado
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: Como reproduzir
      placeholder: |
        1. Vá em ...
        2. Clique em ...
        3. Veja o erro ...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Comportamento esperado
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Comportamento atual
    validations:
      required: true
  - type: input
    id: env
    attributes:
      label: Ambiente
      placeholder: "Browser, OS, Node version, branch/commit"
  - type: textarea
    id: logs
    attributes:
      label: Logs / Screenshots
